/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Home.java
 *
 * Created on 11 Jan, 2012, 12:51:17 PM
 */

package softwarelabapp1;

/**
 *
 * @author SONY
 */
public class Home extends javax.swing.JFrame {

    /** Creates new form Home */
    public Home() {
//        initComponents();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Button_New_Customer = new javax.swing.JButton();
        Button_New_Transaction = new javax.swing.JButton();
        Button_Reset_All = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        Label_First_Name = new javax.swing.JLabel();
        Label_Last_Name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Textfeild_First_Name = new javax.swing.JTextField();
        Label_Address = new javax.swing.JLabel();
        Textfield_Last_Name = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        Textfield_DL = new javax.swing.JTextField();
        Button_Submit = new javax.swing.JButton();
        Button_Reset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${background.RGB}"), jDesktopPane1, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        Button_New_Customer.setText("New Customer");
        Button_New_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_New_CustomerActionPerformed(evt);
            }
        });
        Button_New_Customer.setBounds(70, 200, 140, 50);
        jDesktopPane1.add(Button_New_Customer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Button_New_Transaction.setText("New Transaction");
        Button_New_Transaction.setBounds(380, 200, 140, 50);
        jDesktopPane1.add(Button_New_Transaction, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Button_Reset_All.setText("Reset All");
        Button_Reset_All.setBounds(680, 200, 140, 50);
        jDesktopPane1.add(Button_Reset_All, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrame1.setVisible(true);

        Label_First_Name.setFont(new java.awt.Font("Bradley Hand ITC", 2, 18));
        Label_First_Name.setText("First Name");
        Label_First_Name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Label_Last_Name.setFont(new java.awt.Font("Bradley Hand ITC", 2, 18));
        Label_Last_Name.setText("Last Name");

        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 2, 18));
        jLabel1.setText("Driving Licence Number");

        Textfeild_First_Name.setFont(new java.awt.Font("Verdana", 1, 18));
        Textfeild_First_Name.setToolTipText("Enter Your First Name here");

        Label_Address.setFont(new java.awt.Font("Bradley Hand ITC", 2, 18));
        Label_Address.setText("Address");

        Textfield_Last_Name.setFont(new java.awt.Font("Verdana", 1, 18));
        Textfield_Last_Name.setToolTipText("Enter Your Last Name Here");
        Textfield_Last_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Textfield_Last_NameActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Verdana", 1, 18));
        jTextField1.setToolTipText("Enter Your Address");

        Textfield_DL.setFont(new java.awt.Font("Verdana", 1, 18));
        Textfield_DL.setToolTipText("Enter Your Driving Licence Number Here");

        Button_Submit.setFont(new java.awt.Font("Times New Roman", 1, 18));
        Button_Submit.setText("Submit");
        Button_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SubmitActionPerformed(evt);
            }
        });

        Button_Reset.setFont(new java.awt.Font("Times New Roman", 1, 18));
        Button_Reset.setText("Reset");
        Button_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ResetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 30));
        jLabel2.setText("Please Fill The Form");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(Label_First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(Button_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Textfield_DL, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                            .addComponent(Textfield_Last_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                            .addComponent(Textfeild_First_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(331, 331, 331))))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(473, 473, 473)
                .addComponent(jLabel2)
                .addContainerGap(475, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(Textfeild_First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Label_First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Textfield_Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Textfield_DL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(Button_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jInternalFrame1.setBounds(0, 0, 870, 480);
        jDesktopPane1.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_New_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_New_CustomerActionPerformed
        // TODO add your handling code here:
      //  jInternalFrame1.setVisible(true);
    }//GEN-LAST:event_Button_New_CustomerActionPerformed

    private void Button_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_ResetActionPerformed

    private void Button_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_SubmitActionPerformed

    private void Textfield_Last_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Textfield_Last_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Textfield_Last_NameActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_New_Customer;
    private javax.swing.JButton Button_New_Transaction;
    private javax.swing.JButton Button_Reset;
    private javax.swing.JButton Button_Reset_All;
    private javax.swing.JButton Button_Submit;
    private javax.swing.JLabel Label_Address;
    private javax.swing.JLabel Label_First_Name;
    private javax.swing.JLabel Label_Last_Name;
    private javax.swing.JTextField Textfeild_First_Name;
    private javax.swing.JTextField Textfield_DL;
    private javax.swing.JTextField Textfield_Last_Name;
    private javax.swing.JDesktopPane jDesktopPane1;
    public javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
